### ISSUE TITLE
Log in Callback Error

### ISSUE THREAD

**Issue by JasonMKY** [joschan21/quill#17]
I added all the links to the callback in Kinde, does it take time to update? I added all necessary links and still get this callback error...
![image](https://github.com/joschan21/quill/assets/104327713/3f8fcb34-0ca5-4d53-9ade-2a53d1b2e4c2)

Still get this error when trying to log in:
![image](https://github.com/joschan21/quill/assets/104327713/f6e909b1-4678-4ab3-93c1-c79786fec5d5)

**Comment by anand-mukul** [comment]
@JasonMKY 
Callback URL : https://pdf2-beta.vercel.app/api/auth/kinde_callback
                       http://localhost:3000/api/auth/kinde_callback
Logout URL : https://pdf2-beta.vercel.app
                      http://localhost:3000

**Comment by JasonMKY** [comment]
> @JasonMKY Callback URL : https://pdf2-beta.vercel.app/api/auth/kinde_callback http://localhost:3000/api/auth/kinde_callback Logout URL : https://pdf2-beta.vercel.app http://localhost:3000

Still getting the error

**Comment by anand-mukul** [comment]
@JasonMKY  clear cache and try again

**Comment by JasonMKY** [comment]
> @JasonMKY clear cache and try again

Cleared caches and tried in incognito mode, error still there:
![image](https://github.com/joschan21/quill/assets/104327713/c5d03632-f4c9-4973-866b-23d2edb67b64)

**Comment by anand-mukul** [comment]
@JasonMKY  There is problem in your env, Recheck that 
Also, share your  ..src\lib\utils.ts

**Comment by JasonMKY** [comment]
I put everything correctly in environment setup
![image](https://github.com/joschan21/quill/assets/104327713/3f79e1a1-efb0-47e5-ab1d-6bff28a8ede6)

Src/lib/utils.ts file:

```
import { type ClassValue, clsx } from 'clsx'
import { Metadata } from 'next'
import { twMerge } from 'tailwind-merge'

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

export function absoluteUrl(path: string) {
  if (typeof window !== 'undefined') return path
  if (process.env.VERCEL_URL)
    return `https://${process.env.VERCEL_URL}${path}`
  return `http://localhost:${
    process.env.PORT ?? 3000
  }${path}`
}

export function constructMetadata({
  title = "Quill - the SaaS for students",
  description = "Quill is an open-source software to make chatting to your PDF files easy.",
  image = "/thumbnail.png",
  icons = "/favicon.ico",
  noIndex = false
}: {
  title?: string
  description?: string
  image?: string
  icons?: string
  noIndex?: boolean
} = {}): Metadata {
  return {
    title,
    description,
    openGraph: {
      title,
      description,
      images: [
        {
          url: image
        }
      ]
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [image],
      creator: "@joshtriedcoding"
    },
    icons,
    metadataBase: new URL('https://quill-jet.vercel.app'),
    themeColor: '#FFF',
    ...(noIndex && {
      robots: {
        index: false,
        follow: false
      }
    })
  }
  ```

**Comment by anand-mukul** [comment]
![image](https://github.com/joschan21/quill/assets/147015644/865eae64-5df2-4446-9c41-c6a04c798ce0)

Go to... Kinde>Application>Quick Start

Existing codebase

https://pdf2-beta.vercel.app Edit the link

You will get environment vars

**Comment by JasonMKY** [comment]
**EDIT: Fixed**

When I log in/register this error is showing when going to "/dashboard"

![image](https://github.com/joschan21/quill/assets/104327713/4fc4cad6-c6fb-404c-a5d5-3ab7d6a04f99)


### Error in Log:

**Status Code 200**

![image](https://github.com/joschan21/quill/assets/104327713/a9d0e16b-9401-407a-bfde-45b8e035c4b7)
![image](https://github.com/joschan21/quill/assets/104327713/2c5af75f-7fcc-49e6-a4ac-087cad091317)

**Code in blue highlight below**

```
PrismaClientKnownRequestError: 
Invalid `prisma.user.findFirst()` invocation:


The table `(not available)` does not exist in the current database.
    at wn.handleRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.3.1_prisma@5.3.1/node_modules/@prisma/client/runtime/library.js:123:6730)
    at wn.handleAndLogRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.3.1_prisma@5.3.1/node_modules/@prisma/client/runtime/library.js:123:6119)
    at wn.request (/var/task/node_modules/.pnpm/@prisma+client@5.3.1_prisma@5.3.1/node_modules/@prisma/client/runtime/library.js:123:5839)
    at async l (/var/task/node_modules/.pnpm/@prisma+client@5.3.1_prisma@5.3.1/node_modules/@prisma/client/runtime/library.js:128:9763)
    at async m (/var/task/.next/server/app/dashboard/page.js:1:8592) {
  code: 'P2021',
  clientVersion: '5.3.1',
  meta: { table: '(not available)' }
}
[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '2695897097'
}
PrismaClientKnownRequestError: 
Invalid `prisma.user.findFirst()` invocation:


The table `(not available)` does not exist in the current database.
    at wn.handleRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.3.1_prisma@5.3.1/node_modules/@prisma/client/runtime/library.js:123:6730)
    at wn.handleAndLogRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.3.1_prisma@5.3.1/node_modules/@prisma/client/runtime/library.js:123:6119)
    at wn.request (/var/task/node_modules/.pnpm/@prisma+client@5.3.1_prisma@5.3.1/node_modules/@prisma/client/runtime/library.js:123:5839)
    at async l (/var/task/node_modules/.pnpm/@prisma+client@5.3.1_prisma@5.3.1/node_modules/@prisma/client/runtime/library.js:128:9763)
    at async u (/var/task/.next/server/chunks/753.js:1:732)
    at async z (/var/task/.next/server/chunks/951.js:1:13423) {
  code: 'P2021',
  clientVersion: '5.3.1',
  meta: { table: '(not available)' }
}
[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '341264739'
}
```

**Comment by suzushi-tw** [comment]
> anand

HI anand, first of all thanks for all the otherpost as it helped me overcome some issue. I have no idea if my current problem relate to the other post. First I was getting 500internal error while signing in. And after someadjustment I was able to solve it and get to the registerpage. This time able to register and receive the authentication code (I double checked in kinde that I successfully registered). But then instead of getting routed to the dashboard. I just get 404 Page not found. Any idea on how to solve this?

**Comment by anand-mukul** [comment]
Have you watched @joschan21 Tutorials? You can find it here: https://youtu.be/ucX2zXAZ1I0?si=XN9jWmqWNtRJsPUD

Alternatively, did you set up your own .env credentials? I noticed in your code that you haven't made any changes. I recommend updating it according to your .env credentials. Once you do that, you'll be good to go, @suzushi-tw ! 👍

**Comment by suzushi-tw** [comment]
> Have you watched @joschan21 Tutorials? You can find it here: https://youtu.be/ucX2zXAZ1I0?si=XN9jWmqWNtRJsPUD
> 
> Alternatively, did you set up your own .env credentials? I noticed in your code that you haven't made any changes. I recommend updating it according to your .env credentials. Once you do that, you'll be good to go, @suzushi-tw ! 👍

Actually that was just a repo to test eveything out including the domain. I am following the tutorial on local and I have the enviroment variable set up properly as well. An update on what was happening, basically it was telling me images.remotepatterns missing so I setup those in next.config.js. And a bit of trying around, now I can get to the dashboard. I am currently stuck on uploadthing, as it gives me fetch error. Even though I can see the file being uploaded into the server. The error looks like the following pic. 
![Screenshot 2023-10-16 105713](https://github.com/joschan21/quill/assets/141501059/517c1b4e-279e-432d-aae2-816feddc938f)

I have rewatched the video about this part a few times and couln't figure it out yet. Any suggestions?

**Comment by anand-mukul** [comment]
Please give it a star and check out this repository: https://github.com/anand-mukul/PDFNinja. Since I am unable to find your code, I can't identify the exact issue.

Check 2nd line of your picture it's https://https://stellar......

**Comment by JasonMKY** [comment]
> Please give it a star and check out this repository: https://github.com/anand-mukul/PDFNinja. Since I am unable to find your code, I can't identify the exact issue.
> 
> Check 2nd line of your picture it's https://https://stellar......

I've made the repository public, I searched for "https://https://stellar" in the code but can't find it.

**Comment by anand-mukul** [comment]
```typescript
import React, { useEffect, useState } from 'react';
``` 
Reference: https://github.com/anand-mukul/PDFNinja/blob/main/src/components/UserAccountNav.tsx

**Comment by KLGH24** [comment]
@anand-mukul I checked out PDFNinja and I am unable to interact with the pdf. It's the same error I am getting 404. Is this due to Pinecone changes not allowing name spaces for free anymore?

**Comment by ck18sss** [comment]
> I added all the links to the callback in Kinde, does it take time to update? I added all necessary links and still get this callback error... ![image](https://private-user-images.githubusercontent.com/104327713/275074389-3f8fcb34-0ca5-4d53-9ade-2a53d1b2e4c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NzYwMTIsIm5iZiI6MTcwMzY3NTcxMiwicGF0aCI6Ii8xMDQzMjc3MTMvMjc1MDc0Mzg5LTNmOGZjYjM0LTBjYTUtNGQ1My05YWRlLTJhNTNkMWIyZTRjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyN1QxMTE1MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZGJiMmNhNzQ0NWViOTdmNDEwYjQ0ZmVjNTFmMWE0YWM3Y2QxOGVmYzBjOTE2MWFkMDI1ZGIzMDUxNTY3YTRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6HQyjEV_y9ie599cgdjuEHwggzm8UixGGFQ-5FIlRBc)
> 
> Still get this error when trying to log in: ![image](https://private-user-images.githubusercontent.com/104327713/275074621-f6e909b1-4678-4ab3-93c1-c79786fec5d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NzYwMTIsIm5iZiI6MTcwMzY3NTcxMiwicGF0aCI6Ii8xMDQzMjc3MTMvMjc1MDc0NjIxLWY2ZTkwOWIxLTQ2NzgtNGFiMy05M2MxLWM3OTc4NmZlYzVkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyN1QxMTE1MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xY2E2YTEzYzExMzhiMDhiYTNiMWUwNjc4Y2QxY2U4OTRjNWNkYTA2OTA1YTk2NjBmMzdlMWFmNzllNWJlMGVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.V6baVMz-9P0kHRctPTLMkJ2GDue6RpoJm14eYMPXQL0)

I'm still struggling with this issue unfortunately. My auth won't work, keep getting a callback error when everything is correct.

**Comment by AutomatykaJava** [comment]
You can try alternative way to remove and add callbacks in kinde. Did not tried it yet, but in their documentation there are endpoints to do it. Maybe this is a way.
