### ISSUE TITLE
Pincone.ts

### ISSUE THREAD

**Issue by Obercasa13** [joschan21/quill#64]
I've a few problems with pinecone. Knows somebody now the actual code for the pinecone.ts and how to initalize it in the core.ts? Thanks in advance :))

**Comment by mohit4bug** [comment]
I've fixed it!

# Changes to be done

## Download latest packages for langchain
```bash
npm i @langchain/openai @langchain/pinecone @pinecone-database/pinecone
```
## Imports
```javascript
import { PineconeStore } from '@langchain/pinecone';
import { Pinecone } from '@pinecone-database/pinecone';
import { OpenAIEmbeddings } from '@langchain/openai';
```
## Pinecone Initialization
Pinecone docs says "Instantiate a new Pinecone client, which will automatically read the env vars: PINECONE_API_KEY and PINECONE_ENVIRONMENT which come from the Pinecone dashboard"
```javascript
const pinecone = new Pinecone();
const pineconeIndex = pinecone.Index(process.env.PINECONE_INDEX!);
```
![pinecone](https://github.com/joschan21/quill/assets/106902205/ec86c2d3-0957-4203-930f-15bbe25eb4be)
so You just need to initialize it with keys in `.env` file

## OpenAI Embeddings
This must be same for yours as well, incase if not write this code
```javascript
const embeddings = new OpenAIEmbeddings({
      openAIApiKey: process.env.OPENAI_API_KEY!
});
```
## TypeScript fix
Now your typescript error must be gone here
```javascript
await PineconeStore.fromDocuments(pageLevelDocs, embeddings, {
      pineconeIndex,
      namespace: doc.id,
});
```

**Comment by Obercasa13** [comment]
First of all, thank you very much for the help. I've tried out your instructions, but unfortunately, now there are other errors. Maybe you have another idea where the problem lies;
<img width="766" alt="Screenshot 2024-02-03 at 10 18 39" src="https://github.com/joschan21/quill/assets/133664826/85887222-2771-4fd5-b623-556e0e29a15f">

**Comment by Obercasa13** [comment]
in Terminal i get this:
(base) timoberhaus@Tims-MBP quill % npm run dev

> quill@0.1.0 dev
> next dev

/bin/sh: pnpm: command not found
  ▲ Next.js 13.5.6
  - Local:        http://localhost:3000
  - Environments: .env

 ✓ Ready in 1209ms
(node:57248) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 ✓ Compiled /page in 2.4s (1340 modules)
 ✓ Compiled in 278ms (466 modules)
 ✓ Compiled /favicon.ico/route in 866ms (1356 modules)
 ✓ Compiled /src/middleware in 155ms (253 modules)
 ✓ Compiled /dashboard/page in 435ms (1516 modules)
 ✓ Compiled /api/trpc/[trpc]/route in 162ms (1011 modules)
 ✓ Compiled /dashboard/[fileid]/page in 866ms (2869 modules)
 ✓ Compiled /api/message/route in 859ms (1819 modules)
 ⨯ PineconeArgumentError: The argument to describeIndex had type errors: argument must be string.
    at eval (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/validator.js:223:19)
    at eval (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/control/describeIndex.js:148:25)
    at step (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/control/describeIndex.js:107:23)
    at Object.eval [as next] (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/control/describeIndex.js:48:20)
    at eval (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/control/describeIndex.js:26:71)
    at new Promise (<anonymous>)
    at __awaiter (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/control/describeIndex.js:8:12)
    at eval (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/control/describeIndex.js:143:16)
    at eval (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/indexHostSingleton.js:149:77)
    at step (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/indexHostSingleton.js:107:23)
    at Object.eval [as next] (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/indexHostSingleton.js:48:20)
    at eval (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/indexHostSingleton.js:26:71)
    at new Promise (<anonymous>)
    at __awaiter (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/indexHostSingleton.js:8:12)
    at _describeIndex (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/indexHostSingleton.js:139:16)
    at Object.eval (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/indexHostSingleton.js:193:33)
    at step (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/indexHostSingleton.js:107:23)
    at Object.eval [as next] (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/indexHostSingleton.js:48:20)
    at eval (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/indexHostSingleton.js:26:71)
    at new Promise (<anonymous>)
    at __awaiter (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/indexHostSingleton.js:8:12)
    at Object.getHostUrl (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/indexHostSingleton.js:176:20)
    at VectorOperationsProvider.eval (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/vectorOperationsProvider.js:163:69)
    at step (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/vectorOperationsProvider.js:107:23)
    at Object.eval [as next] (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/vectorOperationsProvider.js:48:20)
    at eval (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/vectorOperationsProvider.js:26:71)
    at new Promise (<anonymous>)
    at __awaiter (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/vectorOperationsProvider.js:8:12)
    at VectorOperationsProvider.provide (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/vectorOperationsProvider.js:139:16)
    at QueryCommand.eval (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/query.js:180:46)
    at step (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/query.js:117:23)
    at Object.eval [as next] (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/query.js:58:20)
    at eval (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/query.js:36:71)
    at new Promise (<anonymous>)
    at __awaiter (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/query.js:18:12)
    at QueryCommand.run (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/query.js:172:16)
    at Index.eval (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/index.js:454:48)
    at step (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/index.js:107:23)
    at Object.eval [as next] (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/index.js:48:20)
    at eval (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/index.js:26:71)
    at new Promise (<anonymous>)
    at __awaiter (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/index.js:8:12)
    at Index.query (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/index.js:448:16)
    at PineconeStore._runPineconeQuery (webpack-internal:///(rsc)/./node_modules/@langchain/pinecone/dist/vectorstores.js:152:41)
    at PineconeStore.similaritySearchVectorWithScore (webpack-internal:///(rsc)/./node_modules/@langchain/pinecone/dist/vectorstores.js:169:36)
    at PineconeStore.similaritySearch (webpack-internal:///(rsc)/./node_modules/@langchain/core/dist/vectorstores.js:117:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async POST (webpack-internal:///(rsc)/./src/app/api/message/route.ts:58:21)
    at async /Users/timoberhaus/quill/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:62499 {
  cause: undefined
}
 ⨯ PineconeArgumentError: The argument to describeIndex had type errors: argument must be string.
    at eval (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/validator.js:223:19)
    at eval (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/control/describeIndex.js:148:25)
    at step (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/control/describeIndex.js:107:23)
    at Object.eval [as next] (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/control/describeIndex.js:48:20)
    at eval (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/control/describeIndex.js:26:71)
    at new Promise (<anonymous>)
    at __awaiter (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/control/describeIndex.js:8:12)
    at eval (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/control/describeIndex.js:143:16)
    at eval (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/indexHostSingleton.js:149:77)
    at step (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/indexHostSingleton.js:107:23)
    at Object.eval [as next] (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/indexHostSingleton.js:48:20)
    at eval (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/indexHostSingleton.js:26:71)
    at new Promise (<anonymous>)
    at __awaiter (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/indexHostSingleton.js:8:12)
    at _describeIndex (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/indexHostSingleton.js:139:16)
    at Object.eval (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/indexHostSingleton.js:193:33)
    at step (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/indexHostSingleton.js:107:23)
    at Object.eval [as next] (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/indexHostSingleton.js:48:20)
    at eval (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/indexHostSingleton.js:26:71)
    at new Promise (<anonymous>)
    at __awaiter (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/indexHostSingleton.js:8:12)
    at Object.getHostUrl (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/indexHostSingleton.js:176:20)
    at VectorOperationsProvider.eval (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/vectorOperationsProvider.js:163:69)
    at step (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/vectorOperationsProvider.js:107:23)
    at Object.eval [as next] (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/vectorOperationsProvider.js:48:20)
    at eval (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/vectorOperationsProvider.js:26:71)
    at new Promise (<anonymous>)
    at __awaiter (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/vectorOperationsProvider.js:8:12)
    at VectorOperationsProvider.provide (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/vectorOperationsProvider.js:139:16)
    at QueryCommand.eval (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/query.js:180:46)
    at step (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/query.js:117:23)
    at Object.eval [as next] (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/query.js:58:20)
    at eval (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/query.js:36:71)
    at new Promise (<anonymous>)
    at __awaiter (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/query.js:18:12)
    at QueryCommand.run (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/query.js:172:16)
    at Index.eval (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/index.js:454:48)
    at step (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/index.js:107:23)
    at Object.eval [as next] (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/index.js:48:20)
    at eval (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/index.js:26:71)
    at new Promise (<anonymous>)
    at __awaiter (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/index.js:8:12)
    at Index.query (webpack-internal:///(rsc)/./node_modules/@pinecone-database/pinecone/dist/data/index.js:448:16)
    at PineconeStore._runPineconeQuery (webpack-internal:///(rsc)/./node_modules/@langchain/pinecone/dist/vectorstores.js:152:41)
    at PineconeStore.similaritySearchVectorWithScore (webpack-internal:///(rsc)/./node_modules/@langchain/pinecone/dist/vectorstores.js:169:36)
    at PineconeStore.similaritySearch (webpack-internal:///(rsc)/./node_modules/@langchain/core/dist/vectorstores.js:117:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async POST (webpack-internal:///(rsc)/./src/app/api/message/route.ts:58:21)
    at async /Users/timoberhaus/quill/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:62499 {
  cause: undefined

**Comment by mohit4bug** [comment]
> First of all, thank you very much for the help. I've tried out your instructions, but unfortunately, now there are other errors. Maybe you have another idea where the problem lies; <img alt="Screenshot 2024-02-03 at 10 18 39" width="766" src="https://private-user-images.githubusercontent.com/133664826/302026079-85887222-2771-4fd5-b623-556e0e29a15f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxOTg2ODksIm5iZiI6MTcwNzE5ODM4OSwicGF0aCI6Ii8xMzM2NjQ4MjYvMzAyMDI2MDc5LTg1ODg3MjIyLTI3NzEtNGZkNS1iNjIzLTU1NmUwZTI5YTE1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNlQwNTQ2MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05N2Q0NGFmM2JkNGY1YTRmNWY3YWE3YTM3ZjBhOTJiY2M1ZGJjYWRlYmZkODkyNDNlNzlkYzk4YjQyY2Q5ZGMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YNAOOaV6ORTHSIM4QXR4FNH_Jvih4fScG3qQi1quDjc">

I'm sorry, I'm not really making the whole app. I was just watching Josh's video for learnings.

**Comment by Jay-Lokhande** [comment]
Hey I used SupaBase and it worked

**Comment by mohit4bug** [comment]
Glad it worked for you!
